apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-deployment
  labels:
    app: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - name: jira
        image: atlassian/jira-software:latest
        ports:
        - containerPort: 8080
        env:
        - name: JVM_SUPPORT_RECOMMENDED_ARGS
          value: "-Dapplinks.allow.all.hosts=true"
        volumeMounts:
        - mountPath: /var/atlassian/application-data/jira
          name: jira-storage
      volumes:
      - name: jira-storage
        persistentVolumeClaim:
          claimName: jira-pvc
