apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /run/desktop/mnt/host/c/pia_data/devops/jira/app
    type: DirectoryOrCreate
  storageClassName: hostpath
