apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 31200
    targetPort: 5672
    nodePort: 31200
  type: NodePort
