apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-postgres-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /run/desktop/mnt/host/c/pia_data/devops/auth/db
  storageClassName: hostpath
