apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: confluence-postgres-pv

