apiVersion: v1
kind: Service
metadata:
  name: confluence-postgres-service
spec:
  selector:
    app: confluence-postgres
  ports:
  - protocol: TCP
    port: 30101
    targetPort: 5432
  type: ClusterIP

