apiVersion: v1
kind: Service
metadata:
  name: confluence-service
spec:
  selector:
    app: confluence
  ports:
  - protocol: TCP
    port: 30100
    targetPort: 8090
    nodePort: 30100
  type: NodePort
