apiVersion: v1
kind: Service
metadata:
  name: confluence-service
spec:
  selector:
    app: confluence
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
    nodePort: 30001
  type: NodePort
