apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres-deployment
  labels:
    app: auth-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
      - name: auth-postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: auth-db
        - name: POSTGRES_USER
          value: auth-user
        - name: POSTGRES_PASSWORD
          value: auth-password
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: "auth-postgres-storage"
      volumes:
      - name: auth-postgres-storage
        persistentVolumeClaim:
          claimName: auth-postgres-pvc
